### ISSUE TITLE
cannot yarn

### ISSUE THREAD

**Issue by sbsrouteur** [Matthieu69007/TrackerWorld#1]
When cloning and running Yarn, I get this:
```
PS D:\Projets\01 - Perso\TrackerWorld> yarn
➤ YN0000: ┌ Resolution step
➤ YN0013: │ cesium-loader@file:plugins/cesium-loader#plugins/cesium-loader::hash=2cab95&locator=my-website%40workspace%3A. can't be found in the cache and will be fetched from the disk
➤ YN0032: │ evp_bytestokey@npm:1.0.3: Implicit dependencies on node-gyp are discouraged
➤ YN0001: │ Error: cesium-loader@file:plugins/cesium-loader#plugins/cesium-loader::hash=2cab95&locator=my-website%40workspace%3A.: Manifest not found
    at Function.find (C:\Users\sbs.INTEST\AppData\Local\Volta\tools\image\yarn\3.6.1\bin\yarn.js:390:32033)
    at async C:\Users\sbs.INTEST\AppData\Local\Volta\tools\image\yarn\3.6.1\bin\yarn.js:601:5030
    at async Object.s0e (C:\Users\sbs.INTEST\AppData\Local\Volta\tools\image\yarn\3.6.1\bin\yarn.js:390:11001)
    at async Hb.resolve (C:\Users\sbs.INTEST\AppData\Local\Volta\tools\image\yarn\3.6.1\bin\yarn.js:601:4991)
    at async kf.resolve (C:\Users\sbs.INTEST\AppData\Local\Volta\tools\image\yarn\3.6.1\bin\yarn.js:391:1400)
    at async kf.resolve (C:\Users\sbs.INTEST\AppData\Local\Volta\tools\image\yarn\3.6.1\bin\yarn.js:391:1400)
    at async C:\Users\sbs.INTEST\AppData\Local\Volta\tools\image\yarn\3.6.1\bin\yarn.js:439:6681
    at async df (C:\Users\sbs.INTEST\AppData\Local\Volta\tools\image\yarn\3.6.1\bin\yarn.js:390:11064)
    at async _ (C:\Users\sbs.INTEST\AppData\Local\Volta\tools\image\yarn\3.6.1\bin\yarn.js:439:6663)
➤ YN0000: └ Completed in 3s 492ms
➤ YN0000: Failed with errors in 3s 501ms
➤ YN0032: fsevents@npm:2.3.2: Implicit dependencies on node-gyp are discouraged
➤ YN0061: stable@npm:0.1.8 is deprecated: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
➤ YN0061: trim@npm:0.0.1 is deprecated: Use String.prototype.trim() instead
PS D:\Projets\01 - Perso\TrackerWorld>
```
What is missing in my setup?

**Comment by sbsrouteur** [comment]
use npm
